// frontend/src/components/shared/EmptyState.tsx
import { type ReactNode } from 'react'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'

interface EmptyStateProps {
  icon: ReactNode
  title: string
  description?: string
  action?: { label: string; onClick: () => void }
}

export function EmptyState({ icon, title, description, action }: EmptyStateProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col items-center justify-center py-24 px-8 text-center"
    >
      <div className="w-14 h-14 rounded-2xl bg-muted flex items-center justify-center mb-4 text-muted-foreground">
        {icon}
      </div>
      <h3 className="text-sm font-semibold text-foreground mb-1">{title}</h3>
      {description && (
        <p className="text-xs text-muted-foreground max-w-[240px]">{description}</p>
      )}
      {action && (
        <Button variant="outline" size="sm" onClick={action.onClick} className="mt-4">
          {action.label}
        </Button>
      )}
    </motion.div>
  )
}

// frontend/src/shared/ui/EmptyState.vue
<script setup lang="ts">
defineProps<{
  title?: string
  description?: string
  icon?: string
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-12 px-4 text-center">
    <div class="w-16 h-16 rounded-full bg-[var(--color-neutral-150)] flex items-center justify-center text-2xl text-[var(--color-text-tertiary)] mb-4">
      <slot name="icon">
        <span>{{ icon || '🔍' }}</span>
      </slot>
    </div>
    <h3 class="text-base font-semibold text-[var(--color-text-primary)] mb-1">
      {{ title || '暂无数据' }}
    </h3>
    <p v-if="description" class="text-sm text-[var(--color-text-secondary)] max-w-sm mb-4">
      {{ description }}
    </p>
    <div v-if="$slots.action" class="mt-2">
      <slot name="action" />
    </div>
  </div>
</template>
